#############################################################################
# Makefile for building: solitaire
# Generated by qmake (2.01a) (Qt 4.8.7) on: Thu May 4 20:47:33 2017
# Project:  solitaire.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile solitaire.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -std=c++11 -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		card.cpp \
		save.cpp \
		table.cpp \
		pile.cpp moc_mainwindow.cpp \
		qrc_cards.cpp
OBJECTS       = main.o \
		mainwindow.o \
		card.o \
		save.o \
		table.o \
		pile.o \
		moc_mainwindow.o \
		qrc_cards.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		solitaire.pro
QMAKE_TARGET  = solitaire
DESTDIR       = 
TARGET        = solitaire

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: solitaire.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile solitaire.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile solitaire.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/solitaire1.0.0 || $(MKDIR) .tmp/solitaire1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/solitaire1.0.0/ && $(COPY_FILE) --parents mainwindow.h card.h save.h table.h .tmp/solitaire1.0.0/ && $(COPY_FILE) --parents playing-cards-assets-master/png/cards.qrc .tmp/solitaire1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp card.cpp save.cpp table.cpp pile.cpp .tmp/solitaire1.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/solitaire1.0.0/ && (cd `dirname .tmp/solitaire1.0.0` && $(TAR) solitaire1.0.0.tar solitaire1.0.0 && $(COMPRESS) solitaire1.0.0.tar) && $(MOVE) `dirname .tmp/solitaire1.0.0`/solitaire1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/solitaire1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: mainwindow.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

compiler_rcc_make_all: qrc_cards.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_cards.cpp
qrc_cards.cpp: playing-cards-assets-master/png/cards.qrc \
		playing-cards-assets-master/png/3_of_hearts.png \
		playing-cards-assets-master/png/queen_of_hearts.png \
		playing-cards-assets-master/png/ace_of_spades.png \
		playing-cards-assets-master/png/6_of_spades.png \
		playing-cards-assets-master/png/6_of_diamonds.png \
		playing-cards-assets-master/png/5_of_clubs.png \
		playing-cards-assets-master/png/king_of_clubs.png \
		playing-cards-assets-master/png/5_of_diamonds.png \
		playing-cards-assets-master/png/7_of_hearts.png \
		playing-cards-assets-master/png/4_of_clubs.png \
		playing-cards-assets-master/png/jack_of_diamonds.png \
		playing-cards-assets-master/png/3_of_clubs.png \
		playing-cards-assets-master/png/2_of_spades.png \
		playing-cards-assets-master/png/2_of_clubs.png \
		playing-cards-assets-master/png/black_joker.png \
		playing-cards-assets-master/png/9_of_clubs.png \
		playing-cards-assets-master/png/ace_of_hearts.png \
		playing-cards-assets-master/png/4_of_hearts.png \
		playing-cards-assets-master/png/3_of_diamonds.png \
		playing-cards-assets-master/png/8_of_clubs.png \
		playing-cards-assets-master/png/7_of_spades.png \
		playing-cards-assets-master/png/7_of_clubs.png \
		playing-cards-assets-master/png/queen_of_diamonds.png \
		playing-cards-assets-master/png/red_joker.png \
		playing-cards-assets-master/png/6_of_clubs.png \
		playing-cards-assets-master/png/ace_of_clubs.png \
		playing-cards-assets-master/png/8_of_hearts.png \
		playing-cards-assets-master/png/king_of_spades.png \
		playing-cards-assets-master/png/9_of_diamonds.png \
		playing-cards-assets-master/png/3_of_spades.png \
		playing-cards-assets-master/png/jack_of_clubs.png \
		playing-cards-assets-master/png/8_of_spades.png \
		playing-cards-assets-master/png/4_of_diamonds.png \
		playing-cards-assets-master/png/5_of_hearts.png \
		playing-cards-assets-master/png/ace_of_diamonds.png \
		playing-cards-assets-master/png/10_of_diamonds.png \
		playing-cards-assets-master/png/queen_of_spades.png \
		playing-cards-assets-master/png/4_of_spades.png \
		playing-cards-assets-master/png/7_of_diamonds.png \
		playing-cards-assets-master/png/2_of_diamonds.png \
		playing-cards-assets-master/png/9_of_hearts.png \
		playing-cards-assets-master/png/jack_of_hearts.png \
		playing-cards-assets-master/png/2_of_hearts.png \
		playing-cards-assets-master/png/king_of_diamonds.png \
		playing-cards-assets-master/png/10_of_hearts.png \
		playing-cards-assets-master/png/9_of_spades.png \
		playing-cards-assets-master/png/jack_of_spades.png \
		playing-cards-assets-master/png/6_of_hearts.png \
		playing-cards-assets-master/png/10_of_clubs.png \
		playing-cards-assets-master/png/10_of_spades.png \
		playing-cards-assets-master/png/queen_of_clubs.png \
		playing-cards-assets-master/png/8_of_diamonds.png \
		playing-cards-assets-master/png/cards.qrc \
		playing-cards-assets-master/png/king_of_hearts.png \
		playing-cards-assets-master/png/5_of_spades.png \
		playing-cards-assets-master/png/back@2x.png \
		playing-cards-assets-master/png/back.png
	/usr/lib/x86_64-linux-gnu/qt4/bin/rcc -name cards playing-cards-assets-master/png/cards.qrc -o qrc_cards.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

card.o: card.cpp card.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o card.o card.cpp

save.o: save.cpp save.h \
		card.h \
		table.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o save.o save.cpp

table.o: table.cpp table.h \
		card.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o table.o table.cpp

pile.o: pile.cpp table.h \
		card.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pile.o pile.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

qrc_cards.o: qrc_cards.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_cards.o qrc_cards.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

